-- configure active components here (for now)
Components = {

	-- these MIGHT trigger in legitimate circumstances, beware before enabling
	["client.godmode"] = false, -- protect against force-setting health and SetEntityInvincible
	["client.speedhack"] = false, -- Protect against Cheat Engine Speedhack
	["client.superjump"] = false, -- protect against super jump cheats
	["client.weaponblacklist"] = false, -- blacklist certain weapons in ac_c.lua
	["client.carblacklist"] = false, -- blacklist certain cars in ac_c.lua
	["client.night"] = true, -- anti night vision
	["client.thermal"] = true, -- anti thermal vision
	["client.multidamage"] = true, -- anti multi damage, blocks damage multiplication
	["client.spectate"] = true, -- detects if cheater is spectating other players
	["server.cleartask"] = true, -- detects clearing player tasks, e.g.kicking from car
	["server.explosions"] = true, -- detect abnormal explosion amount, against "blow up server" cheats

	-- these will NEVER trigger under legitimate circumstances
	["generic"] = true, -- generic event detection for cheats exposing themselves on purpose
	["client.duiblacklist"] = true, -- checks for certain runtime textures being created which are used in cheat menus
	["client.bypasshacks"] = true, -- checks if their cheats try to disable certain anticheat components, not exclusive to anticheese
	["client.esx.gcphone"] = true, -- various detections for gcphone crashers/abuse
	["server.esx.eventspam"] = true, -- detects certain esx events being spammed for fast money
	["server.esx.billings"] = true, -- detects certain billing events that include cheat text
	["server.esx.pickup"] = true, -- detects esx crasher via pickup exploit
	["server.chat.spam"] = true, -- detect certain cheats spamming chat
	["server.esx.gcphone"] = true, -- detect gcphone twitter, sms exploits
	["server.esx.callback"] = true, -- detect esx:triggerServerCallback being crashed with malicious messages
	["server.esx.license"] = true, -- detect esx_license SQL Injection exploit
	["server.esx.kashacter"] = true, -- detect kashacters SQL Injection exploit
	["server.jail"] = true, -- detect various jailer exploits
	["server.discordbot"] = true, -- detect a discordbot spam event
	["server.carrypeople"] = true, -- detect a "carrypeople" exploit
	["server.esx.tackle"] = true, -- same as above except for tackling
	["server.dpemotes"] = true, -- detect an emote request spam in dp-emotes
	["server.esx.policejob"] = true, -- detect a ton of exploits in esx_policejob (cuff,drag,putinvehicle,outvehicle..)
	["server.interactionmenu"] = true, -- detect an exploit of SEM_InteractionMenu 
	["server.vrp.runstring"] = true, -- detect and ban users using a Remote Code Execution function in vrp_basic_menu 

	["customflag"] = true, -- resources can trigger this one themselves if they detected something



	-- ONLY TOUCH THESE IF YOU KNOW WHAT YOU ARE DOING!!!!
	["server.blockClientEntities"] = false, -- ONESYNC REQUIRED it blocks **ALL** Clientside Entities, including vehicles, from spawning, they NEED to be spawned serverside.
	-- can either be false, "strict" (no traffic), "relaxed" (traffic will spawn, script spawning blocked) or "inactive" (normal behaviour, clients can spawn entities)
	-- resource-created Vehicles & Entities WILL NOT SPAWN! this needs to be adjusted accordingly for all resources that do this


	-- found an exploit we dont know yet? found a cheat we can take a look at? dont hesitate, help anticheese development.. TODAY!
	-- discord.gg/GugyRU8
}


-- Blacklist Tables
BlacklistedWeapons = {
	`WEAPON_BALL`,
	`WEAPON_RAILGUN`,
	`WEAPON_GARBAGEBAG`,
}


-- Anticheese will attempt to delete these objects when possible, even if they are legitimate
CageObjs = {
	`hei_prop_carrier_radar_1_l1`,
	`v_res_mexball`,
	`prop_rock_1_a`,
	`prop_rock_1_b`,
	`prop_rock_1_c`,
	`prop_rock_1_d`,
	`prop_player_gasmask`,
	`prop_rock_1_e`,
	`prop_rock_1_f`,
	`prop_rock_1_g`,
	`prop_rock_1_h`,
	`prop_test_boulder_01`,
	`prop_test_boulder_02`,
	`prop_test_boulder_03`,
	`prop_test_boulder_04`,
	`apa_mp_apa_crashed_usaf_01a`,
	`ex_prop_exec_crashdp`,
	`apa_mp_apa_yacht_o1_rail_a`,
	`apa_mp_apa_yacht_o1_rail_b`,
	`apa_mp_h_yacht_armchair_01`,
	`apa_mp_h_yacht_armchair_03`,
	`apa_mp_h_yacht_armchair_04`,
	`prop_fnclink_05crnr1`,
	`apa_mp_h_yacht_barstool_01`,
	`apa_mp_h_yacht_bed_01`,
	`apa_mp_h_yacht_bed_02`,
	`apa_mp_h_yacht_coffee_table_01`,
	`apa_mp_h_yacht_coffee_table_02`,
	`apa_mp_h_yacht_floor_lamp_01`,
	`apa_mp_h_yacht_side_table_01`,
	`apa_mp_h_yacht_side_table_02`,
	`apa_mp_h_yacht_sofa_01`,
	`apa_mp_h_yacht_sofa_02`,
	`apa_mp_h_yacht_stool_01`,
	`apa_mp_h_yacht_strip_chair_01`,
	`apa_mp_h_yacht_table_lamp_01`,
	`apa_mp_h_yacht_table_lamp_02`,
	`apa_mp_h_yacht_table_lamp_03`,
	`prop_flag_columbia`,
	`apa_mp_apa_yacht_o2_rail_a`,
	`apa_mp_apa_yacht_o2_rail_b`,
	`apa_mp_apa_yacht_o3_rail_a`,
	`apa_mp_apa_yacht_o3_rail_b`,
	`apa_mp_apa_yacht_option1`,
	`proc_searock_01`,
	`apa_mp_h_yacht_`,
	`apa_mp_apa_yacht_option1_cola`,
	`apa_mp_apa_yacht_option2`,
	`apa_mp_apa_yacht_option2_cola`,
	`apa_mp_apa_yacht_option2_colb`,
	`apa_mp_apa_yacht_option3`,
	`apa_mp_apa_yacht_option3_cola`,
	`apa_mp_apa_yacht_option3_colb`,
	`apa_mp_apa_yacht_option3_colc`,
	`apa_mp_apa_yacht_option3_cold`,
	`apa_mp_apa_yacht_option3_cole`,
	`apa_mp_apa_yacht_jacuzzi_cam`,
	`apa_mp_apa_yacht_jacuzzi_ripple003`,
	`apa_mp_apa_yacht_jacuzzi_ripple1`,
	`apa_mp_apa_yacht_jacuzzi_ripple2`,
	`apa_mp_apa_yacht_radar_01a`,
	`apa_mp_apa_yacht_win`,
	`prop_crashed_heli`,
	`apa_mp_apa_yacht_door`,
	`prop_shamal_crash`,
	`xm_prop_x17_shamal_crash`,
	`apa_mp_apa_yacht_door2`,
	`apa_mp_apa_yacht`,
	`prop_flagpole_2b`,
	`prop_flagpole_2c`,
	`prop_flag_canada`,
	`apa_prop_yacht_float_1a`,
	`apa_prop_yacht_float_1b`,
	`apa_prop_yacht_glass_01`,
	`sr_prop_spec_tube_xxs_01a`,
	`apa_prop_yacht_glass_02`,
	`apa_prop_yacht_glass_03`,
	`apa_prop_yacht_glass_04`,
	`apa_prop_yacht_glass_05`,
	`apa_prop_yacht_glass_06`,
	`apa_prop_yacht_glass_07`,
	`apa_prop_yacht_glass_08`,
	`apa_prop_yacht_glass_09`,
	`apa_prop_yacht_glass_10`,
	`prop_flag_canada_s`,
	`prop_flag_eu`,
	`prop_flag_eu_s`,
	`prop_target_blue_arrow`,
	`prop_target_orange_arrow`,
	`prop_target_purp_arrow`,
	`prop_target_red_arrow`,
	`apa_prop_flag_argentina`,
	`apa_prop_flag_australia`,
	`apa_prop_flag_austria`,
	`apa_prop_flag_belgium`,
	`apa_prop_flag_brazil`,
	`apa_prop_flag_canadat_yt`,
	`apa_prop_flag_china`,
	`apa_prop_flag_columbia`,
	`apa_prop_flag_croatia`,
	`apa_prop_flag_czechrep`,
	`apa_prop_flag_denmark`,
	`apa_prop_flag_england`,
	`apa_prop_flag_eu_yt`,
	`apa_prop_flag_finland`,
	`apa_prop_flag_france`,
	`apa_prop_flag_german_yt`,
	`apa_prop_flag_hungary`,
	`apa_prop_flag_ireland`,
	`apa_prop_flag_israel`,
	`apa_prop_flag_italy`,
	`apa_prop_flag_jamaica`,
	`apa_prop_flag_japan_yt`,
	`apa_prop_flag_canada_yt`,
	`apa_prop_flag_lstein`,
	`apa_prop_flag_malta`,
	`apa_prop_flag_mexico_yt`,
	`apa_prop_flag_netherlands`,
	`apa_prop_flag_newzealand`,
	`apa_prop_flag_nigeria`,
	`apa_prop_flag_norway`,
	`apa_prop_flag_palestine`,
	`apa_prop_flag_poland`,
	`apa_prop_flag_portugal`,
	`apa_prop_flag_puertorico`,
	`apa_prop_flag_russia_yt`,
	`apa_prop_flag_scotland_yt`,
	`apa_prop_flag_script`,
	`apa_prop_flag_slovakia`,
	`apa_prop_flag_slovenia`,
	`apa_prop_flag_southafrica`,
	`apa_prop_flag_southkorea`,
	`apa_prop_flag_spain`,
	`apa_prop_flag_sweden`,
	`apa_prop_flag_switzerland`,
	`apa_prop_flag_turkey`,
	`apa_prop_flag_uk_yt`,
	`apa_prop_flag_us_yt`,
	`apa_prop_flag_wales`,
	`apa_mp_h_bed_double_09`,
	`apa_mp_h_bed_wide_05`,
	`prop_flag_uk`,
	`prop_flag_uk_s`,
	`prop_flag_us`,
	`prop_cattlecrush`,
	`prop_cs_documents_01`,
	`proc_forest_grass01`,
	`ex_props_exec_crashedp`,
	`xm_prop_x17_osphatch_40m`,
	`stt_prop_stunt_soccer_ball`,
	`prop_flag_usboat`,
	`prop_flag_us_r`,
	`prop_flag_us_s`,
	`prop_flag_france`,
	`prop_flag_france_s`,
	`prop_flag_german`,
	`prop_flag_german_s`,
	`prop_flag_ireland`,
	`prop_flag_ireland_s`,
	`prop_flag_japan`,
	`prop_flag_japan_s`,
	`prop_flag_ls`,
	`prop_flag_lsfd`,
	`prop_flag_lsfd_s`,
	`prop_flag_lsservices`,
	`prop_flag_lsservices_s`,
	`prop_mp_ramp_03`,
	`prop_mp_ramp_02`,
	`prop_mp_ramp_01`,
	`prop_container_01a`,
	`prop_container_01b`,
	`prop_mp_barrier_01`,
	`prop_mp_barrier_01b`,
	`prop_mp_barrier_02`,
	`prop_mp_barrier_02b`,
	`prop_flag_ls_s`,
	`prop_flag_mexico`,
	`prop_flag_mexico_s`,
	`prop_flag_russia`,
	`prop_flag_russia_s`,
	`prop_flag_s`,
	`prop_flag_sa`,
	`prop_flag_sapd`,
	`prop_flag_sapd_s`,
	`prop_flag_sa_s`,
	`prop_flag_scotland`,
	`prop_flag_scotland_s`,
	`prop_flag_sheriff`,
	`prop_flag_sheriff_s`,
	`prop_flag_uk`,
	`prop_flag_uk_s`,
	`prop_flag_us`,
	`prop_flag_usboat`,
	`prop_flag_us_r`,
	`prop_flag_us_s`,
	`prop_flamingo`,
	`prop_swiss_ball_01`,
	`prop_air_bigradar_l1`,
	`prop_air_bigradar_l2`,
	`prop_air_bigradar_slod`,
	`p_fib_rubble_s`,
	`prop_money_bag_01`,
	`p_cs_mp_jet_01_s`,
	`prop_poly_bag_money`,
	`prop_air_radar_01`,
	`hei_prop_carrier_radar_1`,
	`prop_air_bigradar`,
	`prop_carrier_radar_1_l1`,
	`prop_asteroid_01`,
	`prop_xmas_ext`,
	`p_oil_pjack_01_amo`,
	`p_oil_pjack_01_s`,
	`p_oil_pjack_02_amo`,
	`p_oil_pjack_03_amo`,
	`p_oil_pjack_02_s`,
	`p_oil_pjack_03_s`,
	`prop_aircon_l_03`,
	`prop_med_jet_01`,
	`p_med_jet_01_s`,
	`hei_prop_carrier_jet`,
	`bkr_prop_biker_bblock_huge_01`,
	`bkr_prop_biker_bblock_huge_02`,
	`bkr_prop_biker_bblock_huge_04`,
	`bkr_prop_biker_bblock_huge_05`,
	`hei_prop_heist_emp`,
	`prop_weed_01`,
	`prop_air_bigradar`,
	`prop_juicestand`,
	`prop_lev_des_barge_02`,
	`hei_prop_carrier_defense_01`,
	`prop_aircon_m_04`,
	`prop_mp_ramp_03`,
	`stt_prop_stunt_track_dwuturn`,
	`ch3_12_animplane1_lod`,
	`ch3_12_animplane2_lod`,
	`hei_prop_hei_pic_pb_plane`,
	`light_plane_rig`,
	`prop_cs_plane_int_01`,
	`prop_dummy_plane`,
	`prop_mk_plane`,
	`v_44_planeticket`,
	`prop_planer_01`,
	`ch3_03_cliffrocks03b_lod`,
	`ch3_04_rock_lod_02`,
	`csx_coastsmalrock_01_`,
	`csx_coastsmalrock_02_`,
	`csx_coastsmalrock_03_`,
	`csx_coastsmalrock_04_`,
	`mp_player_introck`,
	`Heist_Yacht`,
	`csx_coastsmalrock_05_`,
	`mp_player_int_rock`,
	`mp_player_introck`,
	`prop_flagpole_1a`,
	`prop_flagpole_2a`,
	`prop_flagpole_3a`,
	`prop_a4_pile_01`,
	`cs2_10_sea_rocks_lod`,
	`cs2_11_sea_marina_xr_rocks_03_lod`,
	`prop_gold_cont_01`,
	`prop_hydro_platform`,
	`ch3_04_viewplatform_slod`,
	`ch2_03c_rnchstones_lod`,
	`proc_mntn_stone01`,
	`prop_beachflag_le`,
	`proc_mntn_stone02`,
	`cs2_10_sea_shipwreck_lod`,
	`des_shipsink_02`,
	`prop_dock_shippad`,
	`des_shipsink_03`,
	`des_shipsink_04`,
	`prop_mk_flag`,
	`prop_mk_flag_2`,
	`proc_mntn_stone03`,
	`FreeModeMale01`,
	`rsn_os_specialfloatymetal_n`,
	`rsn_os_specialfloatymetal`,
	`cs1_09_sea_ufo`,
	`rsn_os_specialfloaty2_light2`,
	`rsn_os_specialfloaty2_light`,
	`rsn_os_specialfloaty2`,
	`rsn_os_specialfloatymetal_n`,
	`rsn_os_specialfloatymetal`,
	`P_Spinning_Anus_S_Main`,
	`P_Spinning_Anus_S_Root`,
	`cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a`,
	`sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a`,
	`rnbj_wallsigns_0001`,
	`proc_sml_stones01`,
	`proc_sml_stones02`,
	`maverick`,
	`Miljet`,
	`proc_sml_stones03`,
	`proc_stones_01`,
	`proc_stones_02`,
	`proc_stones_03`,
	`proc_stones_04`,
	`proc_stones_05`,
	`proc_stones_06`,
	`prop_coral_stone_03`,
	`prop_coral_stone_04`,
	`prop_gravestones_01a`,
	`prop_gravestones_02a`,
	`prop_gravestones_03a`,
	`prop_gravestones_04a`,
	`prop_gravestones_05a`,
	`prop_gravestones_06a`,
	`prop_gravestones_07a`,
	`prop_gravestones_08a`,
	`prop_gravestones_09a`,
	`prop_gravestones_10a`,
	`prop_prlg_gravestone_05a_l1`,
	`prop_prlg_gravestone_06a`,
	`test_prop_gravestones_04a`,
	`test_prop_gravestones_05a`,
	`test_prop_gravestones_07a`,
	`test_prop_gravestones_08a`,
	`test_prop_gravestones_09a`,
	`prop_prlg_gravestone_01a`,
	`prop_prlg_gravestone_02a`,
	`prop_prlg_gravestone_03a`,
	`prop_prlg_gravestone_04a`,
	`prop_stoneshroom1`,
	`prop_stoneshroom2`,
	`v_res_fa_stones01`,
	`test_prop_gravestones_01a`,
	`test_prop_gravestones_02a`,
	`prop_prlg_gravestone_05a`,
	`FreemodeFemale01`,
	`prop_gas_tank_01a`,
	`prop_gascyl_01a`,
	`p_cablecar_s`,
	`stt_prop_stunt_tube_l`,
	`stt_prop_stunt_track_dwuturn`,
	`p_ferris_car_01`,
	`p_spinning_anus_s`,
	`prop_cj_big_boat`,
	`prop_rock_4_big2`,
	`prop_steps_big_01`,
	`v_ilev_lest_bigscreen`,
	`prop_carcreeper`,
	`prop_windmill_01`,
	`hei_prop_heist_tug`,
	`prop_air_bigradar`,
	`p_oil_slick_01`,
	`prop_dummy_01`,
	`hei_prop_heist_emp`,
	`p_tram_cash_s`,
	`hw1_blimp_ce2`,
	`prop_fire_exting_1a`,
	`prop_fire_exting_1b`,
	`prop_fire_exting_2a`,
	`prop_fire_exting_3a`,
	`hei_prop_carrier_cargo_02a`,
	`hw1_blimp_ce2_lod`,
	`hw1_blimp_ce_lod`,
	`hw1_blimp_cpr003`,
	`hw1_blimp_cpr_null`,
	`hw1_blimp_cpr_null2`,
	`prop_lev_des_barage_02`,
	`hei_prop_carrier_defense_01`,
	`prop_juicestand`,
	`S_M_M_MovAlien_01`,
	`s_m_m_movalien_01`,
	`s_m_m_movallien_01`,
	`u_m_y_babyd`,
	`CS_Orleans`,
	`A_M_Y_ACult_01`,
	`S_M_M_MovSpace_01`,
	`U_M_Y_Zombie_01`,
	`s_m_y_blackops_01`,
	`a_f_y_topless_01`,
	`a_c_boar`,
	`a_c_cat_01`,
	`a_c_chickenhawk`,
	`a_c_chimp`,
	`s_f_y_hooker_03`,
	`a_c_chop`,
	`a_c_cormorant`,
	`a_c_cow`,
	`a_c_coyote`,
	`v_ilev_found_cranebucket`,
	`p_cs_sub_hook_01_s`,
	`a_c_crow`,
	`a_c_dolphin`,
	`a_c_fish`,
	`hei_prop_heist_hook_01`,
	`prop_rope_hook_01`,
	`prop_sub_crane_hook`,
	`s_f_y_hooker_01`,
	`prop_vehicle_hook`,
	`prop_v_hook_s`,
	`prop_dock_crane_02_hook`,
	`prop_winch_hook_long`,
	`a_c_hen`,
	`a_c_humpback`,
	`a_c_husky`,
	`a_c_killerwhale`,
	`a_c_mtlion`,
	`a_c_pigeon`,
	`a_c_poodle`,
	`prop_coathook_01`,
	`prop_cs_sub_hook_01`,
	`a_c_pug`,
	`a_c_rabbit_01`,
	`a_c_rat`,
	`a_c_retriever`,
	`a_c_rhesus`,
	`a_c_rottweiler`,
	`a_c_sharkhammer`,
	`a_c_sharktiger`,
	`a_c_shepherd`,
	`a_c_stingray`,
	`a_c_westy`,
	`CS_Orleans`,
	`prop_windmill_01`,
	`prop_Ld_ferris_wheel`,
	`p_tram_crash_s`,
	`p_oil_slick_01`,
	`p_ld_stinger_s`,
	`p_ld_soc_ball_01`,
	`p_parachute1_s`,
	`p_cablecar_s`,
	`prop_beach_fire`,
	`prop_gas_pump_old2`,
	`prop_vintage_pump`,
	`prop_gas_pump_old3`,
	`prop_gas_pump_1d`,
	`prop_gas_pump_1c`,
	`prop_gas_pump_1b`,
	`prop_gas_pump_1a`,
	`prop_gas_airunit01`,
	`prop_lev_des_barge_02`,
	`prop_lev_des_barge_01`,
	`prop_sculpt_fix`,
	`prop_flagpole_2b`,
	`prop_flagpole_2c`,
	`prop_winch_hook_short`,
	`prop_flag_canada`,
	`prop_flag_canada_s`,
	`prop_flag_eu`,
	`prop_flag_eu_s`,
	`prop_flag_france`,
	`prop_flag_france_s`,
	`prop_flag_german`,
	`prop_ld_hook`,
	`prop_flag_german_s`,
	`prop_flag_ireland`,
	`prop_flag_ireland_s`,
	`prop_flag_japan`,
	`prop_flag_japan_s`,
	`prop_flag_ls`,
	`prop_flag_lsfd`,
	`prop_flag_lsfd_s`,
	`prop_cable_hook_01`,
	`prop_flag_lsservices`,
	`prop_flag_lsservices_s`,
	`prop_flag_ls_s`,
	`prop_flag_mexico`,
	`prop_flag_mexico_s`,
	`csx_coastboulder_00`,
	`des_tankercrash_01`,
	`des_tankerexplosion_01`,
	`des_tankerexplosion_02`,
	`des_trailerparka_02`,
	`des_trailerparkb_02`,
	`des_trailerparkc_02`,
	`des_trailerparkd_02`,
	`des_traincrash_root2`,
	`des_traincrash_root3`,
	`des_traincrash_root4`,
	`des_traincrash_root5`,
	`des_finale_vault_end`,
	`des_finale_vault_root001`,
	`des_finale_vault_root002`,
	`des_finale_vault_root003`,
	`des_finale_vault_root004`,
	`des_finale_vault_start`,
	`des_vaultdoor001_root001`,
	`des_vaultdoor001_root002`,
	`des_vaultdoor001_root003`,
	`des_vaultdoor001_root004`,
	`des_vaultdoor001_root005`,
	`des_vaultdoor001_root006`,
	`des_vaultdoor001_skin001`,
	`des_vaultdoor001_start`,
	`des_traincrash_root6`,
	`prop_ld_vault_door`,
	`prop_vault_door_scene`,
	`prop_vault_door_scene`,
	`prop_vault_shutter`,
	`p_fin_vaultdoor_s`,
	`v_ilev_bk_vaultdoor`,
	`prop_gold_vault_fence_l`,
	`prop_gold_vault_fence_r`,
	`prop_gold_vault_gate_01`,
	`prop_bank_vaultdoor`,
	`des_traincrash_root7`,
	`prop_flag_russia`,
	`prop_flag_russia_s`,
	`prop_flag_s`,
	`ch2_03c_props_rrlwindmill_lod`,
	`prop_flag_sa`,
	`prop_flag_sapd`,
	`prop_flag_sapd_s`,
	`prop_flag_sa_s`,
	`prop_flag_scotland`,
	`prop_flag_scotland_s`,
	`prop_cs_dildo_01`,
	`p_spinning_anus_s`,
	`prop_ld_toilet_01`,
	`prop_flag_sheriff`,
	`prop_ld_farm_couch01`,
	`prop_ld_bomb_anim`,
	`prop_flag_sheriff_s`,
	`prop_flag_uk`,
	`prop_yacht_lounger`,
	`prop_yacht_seat_01`,
	`prop_yacht_seat_02`,
	`prop_yacht_seat_03`,
	`marina_xr_rocks_02`,
	`marina_xr_rocks_03`,
	`prop_test_rocks01`,
	`prop_test_rocks02`,
	`prop_test_rocks03`,
	`prop_test_rocks04`,
	`marina_xr_rocks_04`,
	`marina_xr_rocks_05`,
	`marina_xr_rocks_06`,
	`prop_yacht_table_01`,
	`csx_searocks_02`,
	`csx_searocks_03`,
	`csx_searocks_04`,
	`csx_searocks_05`,
	`csx_searocks_06`,
	`p_yacht_chair_01_s`,
	`p_yacht_sofa_01_s`,
	`prop_yacht_table_02`,
	`csx_coastboulder_00`,
	`csx_coastboulder_01`,
	`csx_coastboulder_02`,
	`csx_coastboulder_03`,
	`csx_coastboulder_04`,
	`csx_coastboulder_05`,
	`csx_coastboulder_06`,
	`csx_coastboulder_07`,
	`csx_coastrok1`,
	`csx_coastrok2`,
	`csx_coastrok3`,
	`csx_coastrok4`,
	`csx_coastsmalrock_01`,
	`csx_coastsmalrock_02`,
	`csx_coastsmalrock_03`,
	`csx_coastsmalrock_04`,
	`csx_coastsmalrock_05`,
	`prop_yacht_table_03`,
	`prop_flag_uk_s`,
	`stt_prop_ramp_adj_loop`,
	`prop_flag_us`,
	`prop_flag_usboat`,
	`prop_flag_us_r`,
	`prop_flag_us_s`,
	`p_gasmask_s`,
	`xm_prop_x17_sub_damage`,
	`xm_prop_x17_sub`,
	`xm_prop_x17_silo_rocket_01`,
	`prop_flamingo`,
	
}

-- list of cars that cannot be spawned
blacklistedCars = {
	-- `khanjali`,
}


-- events which will trigger a ban when they are triggered with a negative amount
negativePayEvents = {
	"neweden_garage:pay",
	"projektsantos:mandathajs",
	"esx_dmvschool:pay"
}


-- text banned from esx_billing, esx_phone and similar inputs
maliciousBillings = {
	"Absolute Menu",
	"d0pamine.xyz",
	"d0pamine_xyz",
	"discord.gg/fjBp55t",
	"RocMenu",
	"Blood-X Menu",
	"Brutan#7799",
	"BRUTAN menu",
	"Lynx10",
	"lynxmenu",
	"Nertigel#5391",
	"Kolorek#1396",
	"https://discord.gg/rMFtEFK",
	"https://discord.gg/kgUtDrC",
	"You've been sent to jail by Cat and Flacko",
	"https://discord.gg/DAhzN6q",
	"Melon#1379",
	"Desudo Executor",
	"ahezu#6666",
	"HamMafia on YOUTUBE",
	"Skrobek on YOUTUBE",
	"https://discord.gg/yJb3qKG",
	"ZAPRASZAM NA KANAŁ THEULAN",
	"https://discord.gg/BEcQrjC"
}


-- messages that may get sent in chat or through other resources which will then broadcast it
-- content warning: may contain racist, sexist or similar sentences and phrases, these are taken directly from cheats
maliciousMessages = {
	"~r~You just got fucked by Falcon",
	"https://discord.gg/y7xyNeG",
	"d0pamine.xyz",
	"d0pamine_xyz",
	"www.d0pamine",
	"discord.gg/fjBp55t",
	"oFlaqme#1325",
	"RocMenu",
	"https://discord.gg/NdzS3Qxa",
	"~g~Brutan#7799",
	"Brutan Premium",
	"Brutan#3927",
	"www.Brutan",
	"https://discordapp.com/invite/tCEajtn",
	"discord.gg/TVxy6HwNSg",
	"^13^24^3B^4y^5T^6e ^1C^2o^3m^4m^5u^6n^7i^1t^2y",
	"https://discord.gg/6wNar8g",
	"discord.gg/eCAZveXq7X",
	"^1L^2y^3n^4x ^5R^6e^7v^8o^9l^1u^2t^3i^5o^4n",
	"Nertigel#5391",
	"MALOSSIHOSTING",
	"https://discord.gg/qyVE4WW",
	"DarkSide-Gang",
	"^13^24^3B^4R^5U^6TAN",
	"discord.gg/DXQvMEzKSd",
	"MalossiHosting",
	"Get Fucked By ^1SugarMafia",
	"Absolute Menu on top",
	"https://discord.gg/GbsQxN",
	"foriv#0002",
	"xAries on YOUTUBE",
	"https://discord.gg/u9CxU33",
	"dc.xaries",
	"Darmowe cheaty na Fivem",
	"BRUTAN ON YOUTUBE",
	"xCat on YOUTUBE",
	"oFlaqme#1149",
	"SHADOW MENU | KOCHAM WAS",
	"Kolorek#1396",
	"https://discord.gg/rMFtEFK",
	"japierdole jak jestescie w wiezienu to ten serwer ssie pale elo",
	"https://discord.gg/kgUtDrC",
	"You've been sent to jail by Cat and Flacko",
	"https://discord.gg/DAhzN6q",
	"Melon#1379",
	"Desudo Executor",
	"ahezu#6666",
	"HamMafia on YOUTUBE",
	"Skrobek on YOUTUBE",
	"https://discord.gg/yJb3qKG",
	"ZAPRASZAM NA KANAŁ THEULAN",
	"https://discord.gg/BEcQrjC",
	"RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"lutfen bankana bak. Sana para gonderdik, bu parayi Alien Menu sayesinde yaptik"
}

-- events which can be used to jail everyone
jailerEvents = {
	"esx_jailer:sendToJail",
	"esx_jailler:sendToJail",
	"esx-qalle-jail:jailPlayer",
	"esx-qalle-jail:jailPlayerNew",
	"esx_jail:sendToJail",
	"esx_jailer:sendToJailCatfrajerze",
	"js:jailuser",
	"wyspa_jail:jailPlayer",
	"wyspa_jail:jail",
	"esx-qalle-jail:updateJailTime",
	"esx-qalle-jail:updateJailTime_n96nDDU@X?@zpf8"
}


-- events which are often spammed and abused by cheats
spammedEvents = {
	"esx_pilot:success",
	"esx_taxijob:success",
	"esx_mugging:giveMoney",
	"paycheck:salary",
	"esx_godirtyjob:pay",
	"esx_pizza:pay",
	"esx_slotmachine:sv:2",
	"esx_banksecurity:pay",
	"esx_gopostaljob:pay",
	"esx_truckerjob:pay",
	"esx_carthief:pay",
	"esx_garbagejob:pay",
	"esx_ranger:pay",
	"esx_truckersjob:payy",
	"PayForRepairNow",
	"reanimar:pagamento",
	"salario:pagamento",
	"offred:salar",
	"gcPhone:sendMessage",
	"esx_jailer:sendToJail",
	"esx_jailler:sendToJail",
	"esx-qalle-jail:jailPlayer",
	"esx-qalle-jail:jailPlayerNew",
	"esx_jail:sendToJail",
	"8321hiue89js",
	"esx_jailer:sendToJailCatfrajerze",
	"js:jailuser",
	"wyspa_jail:jailPlayer",
	"wyspa_jail:jail",
	"esx_policejob:billPlayer",
	"esx-qalle-jail:updateJailTime",
	"esx-qalle-jail:updateJailTime_n96nDDU@X?@zpf8",
	"::{korioz#0110}::jobs_civil:pay",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:startTransformOpium",
	"esx_drugs:startSellOpium",
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startTransformWeed",
	"esx_drugs:startSellWeed",
	"::{korioz#0110}::esx_billing:sendBill",
	"esx_billing:sendBill",
	"esx_mechanicjob:startHarvest",
	"esx_mechanicjob:startHarvest2",
	"esx_mechanicjob:startHarvest3",
	"esx_mechanicjob:startHarvest4",
	"esx_mechanicjob:startCraft",
	"esx_mechanicjob:startCraft2",
	"esx_mechanicjob:startCraft3",
	"esx_bitcoin:startHarvestKoda",
	"esx_bitcoin:startSellKoda",
	"esx_blanchisseur:startWhitening",
	"trip_adminmenu:addMoney",
	"esx_reprogjob:onNPCJobMissionCompleted",
	"esx_ambulancejob:revive",
	"Impulsionjobs_civil:pay",
	"SEM_InteractionMenu:CuffNear",
	"esx_fueldelivery:pay",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:sell",
	"esx_vangelico_robbery:gioielli1",
	"lester:vendita",
	"houseRobberies:giveMoney",
	"lh-bankrobbery:server:recieveItem",
	"esx_uber:pay",
	"99kr-burglary:Add",
	"99kr-shops:Cashier",
	"esx-ecobottles:retrieveBottle",
	"loffe_carthief:questFinished",
	"loffe_fishing:caught",
	"esx_loffe_fangelse:Pay",
	"loffe_robbery:pickUp",
	"hospital:client:Revive",
	"cylex:startSellSarap",
	"cylex:startTransformSarap",
	"cylex:startHarvestSarap",
	"cylex:startSellMelon",
	"cylex:startTransformMelon",
	"cylex:startHarvestMelon",
	"sp_admin:menuv",
	"sp_admin:giveCash",
	"sp_admin:giveDirtyMoney",
	"sp_admin:giveCash"
}
